### ISSUE TITLE
Problems without accepted papers

### ISSUE THREAD

**Issue by rgcmme** [kgb-workshop/sad-generator#25]
When there are no accepted papers yet in the workshop, if the CSV file is empty the script launches an exception and if it only contains the header row (without any accepted paper) it launches another exception in another place.

The index.html file indicates there should be an option to have 0 accepted papers:
`{% if acceptedpapers.size > 0 %}`

**Comment by pheyvaer** [comment]
HI @rgcmme 

Could you tell us the exceptions that you are getting?

**Comment by rgcmme** [comment]
If I run with the accepted-papers.csv only with the header row (i.e., no papers), I get this:

```
15:26:13.648 [main] INFO  be.ugent.rml.cli.Main               .writeOutputUncompressed(294) - 153 quads were generated
15:26:13.650 [main] INFO  be.ugent.rml.cli.Main               .writeOutputUncompressed(306) - Writing quads to data.nt...
15:26:13.675 [main] INFO  be.ugent.rml.cli.Main               .writeOutputUncompressed(324) - Writing to /sad-generator/kg/data.nt is done.
(node:74) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
> Cannot read property '0' of undefined (TypeError):
    TypeError: Cannot read property '0' of undefined
        at result.forEach.paper (/sad-generator/website/_data/acceptedpapers.js:26:27)
        at Array.forEach (<anonymous>)
        at module.exports (/sad-generator/website/_data/acceptedpapers.js:19:10)
```

If I run with the accepted-papers.csv empty (not even the header row), I get this:

```
15:26:34.609 [main] ERROR be.ugent.rml.cli.Main               .main(233) - Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at be.ugent.rml.records.CSV._get(CSV.java:35)
	at be.ugent.rml.records.CSV.get(CSV.java:26)
	at be.ugent.rml.records.RecordsFactory.getCSVRecords(RecordsFactory.java:112)
	at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:62)
	at be.ugent.rml.Executor.getRecords(Executor.java:310)
	at be.ugent.rml.Executor.executeWithFunction(Executor.java:91)
	at be.ugent.rml.Executor.execute(Executor.java:78)
	at be.ugent.rml.cli.Main.main(Main.java:206)
(node:112) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
> Cannot read property '0' of undefined (TypeError):
    TypeError: Cannot read property '0' of undefined
        at result.forEach.paper (/sad-generator/website/_data/acceptedpapers.js:26:27)
        at Array.forEach (<anonymous>)
        at module.exports (/sad-generator/website/_data/acceptedpapers.js:19:10)
```
